use crate::world::blocks::Blocks;

/// TODO: check with forge or fabric for correctness
pub fn is_solid(block: &Blocks) -> bool {
    match block {
        Blocks::Air
        | Blocks::Water(_)
        | Blocks::Lava(_)
        | Blocks::OakSapling(_)
        | Blocks::SpruceSapling(_)
        | Blocks::BirchSapling(_)
        | Blocks::JungleSapling(_)
        | Blocks::AcaciaSapling(_)
        | Blocks::DarkOakSapling(_)
        | Blocks::Dandelion
        | Blocks::Poppy
        | Blocks::BlueOrchid
        | Blocks::Allium
        | Blocks::AzureBluet
        | Blocks::RedTulip
        | Blocks::OrangeTulip
        | Blocks::WhiteTulip
        | Blocks::PinkTulip
        | Blocks::OxeyeDaisy
        | Blocks::Cornflower
        | Blocks::WitherRose
        | Blocks::LilyOfTheValley
        | Blocks::BrownMushroom
        | Blocks::RedMushroom
        | Blocks::Grass
        | Blocks::Fern
        | Blocks::DeadBush
        | Blocks::Seagrass
        | Blocks::TallSeagrass(_)
        | Blocks::Torch
        | Blocks::WallTorch(_)
        | Blocks::Fire(_)
        | Blocks::SoulFire
        | Blocks::Wheat(_)
        | Blocks::OakSign(_)
        | Blocks::SpruceSign(_)
        | Blocks::BirchSign(_)
        | Blocks::AcaciaSign(_)
        | Blocks::JungleSign(_)
        | Blocks::DarkOakSign(_)
        | Blocks::Rail(_)
        | Blocks::OakWallSign(_)
        | Blocks::SpruceWallSign(_)
        | Blocks::BirchWallSign(_)
        | Blocks::AcaciaWallSign(_)
        | Blocks::JungleWallSign(_)
        | Blocks::DarkOakWallSign(_)
        | Blocks::Lever(_)
        | Blocks::StonePressurePlate(_)
        | Blocks::OakPressurePlate(_)
        | Blocks::SprucePressurePlate(_)
        | Blocks::BirchPressurePlate(_)
        | Blocks::JunglePressurePlate(_)
        | Blocks::AcaciaPressurePlate(_)
        | Blocks::DarkOakPressurePlate(_)
        | Blocks::RedstoneTorch(_)
        | Blocks::RedstoneWallTorch(_)
        | Blocks::StoneButton(_)
        | Blocks::SugarCane(_)
        | Blocks::SoulTorch
        | Blocks::SoulWallTorch(_)
        | Blocks::NetherPortal(_)
        | Blocks::Repeater(_)
        | Blocks::AttachedPumpkinStem(_)
        | Blocks::AttachedMelonStem(_)
        | Blocks::PumpkinStem(_)
        | Blocks::MelonStem(_)
        | Blocks::Vine(_)
        | Blocks::GlowLichen(_)
        | Blocks::EndPortal
        | Blocks::TripwireHook(_)
        | Blocks::Tripwire(_)
        | Blocks::FlowerPot
        | Blocks::PottedOakSapling
        | Blocks::PottedSpruceSapling
        | Blocks::PottedBirchSapling
        | Blocks::PottedJungleSapling
        | Blocks::PottedAcaciaSapling
        | Blocks::PottedDarkOakSapling
        | Blocks::PottedFern
        | Blocks::PottedDandelion
        | Blocks::PottedPoppy
        | Blocks::PottedBlueOrchid
        | Blocks::PottedAllium
        | Blocks::PottedAzureBluet
        | Blocks::PottedRedTulip
        | Blocks::PottedOrangeTulip
        | Blocks::PottedWhiteTulip
        | Blocks::PottedPinkTulip
        | Blocks::PottedOxeyeDaisy
        | Blocks::PottedCornflower
        | Blocks::PottedLilyOfTheValley
        | Blocks::PottedWitherRose
        | Blocks::PottedRedMushroom
        | Blocks::PottedBrownMushroom
        | Blocks::PottedDeadBush
        | Blocks::PottedCactus
        | Blocks::Carrots(_)
        | Blocks::Potatoes(_)
        | Blocks::OakButton(_)
        | Blocks::SpruceButton(_)
        | Blocks::BirchButton(_)
        | Blocks::JungleButton(_)
        | Blocks::AcaciaButton(_)
        | Blocks::DarkOakButton(_)
        | Blocks::Comparator(_)
        | Blocks::ActivatorRail(_)
        | Blocks::Light(_)
        | Blocks::WhiteCarpet
        | Blocks::OrangeCarpet
        | Blocks::MagentaCarpet
        | Blocks::LightBlueCarpet
        | Blocks::YellowCarpet
        | Blocks::LimeCarpet
        | Blocks::PinkCarpet
        | Blocks::GrayCarpet
        | Blocks::LightGrayCarpet
        | Blocks::CyanCarpet
        | Blocks::PurpleCarpet
        | Blocks::BlueCarpet
        | Blocks::BrownCarpet
        | Blocks::GreenCarpet
        | Blocks::RedCarpet
        | Blocks::BlackCarpet
        | Blocks::Sunflower(_)
        | Blocks::RoseBush(_)
        | Blocks::Peony(_)
        | Blocks::TallGrass(_)
        | Blocks::LargeFern(_)
        | Blocks::WhiteBanner(_)
        | Blocks::OrangeBanner(_)
        | Blocks::MagentaBanner(_)
        | Blocks::LightBlueBanner(_)
        | Blocks::YellowBanner(_)
        | Blocks::LimeBanner(_)
        | Blocks::PinkBanner(_)
        | Blocks::GrayBanner(_)
        | Blocks::LightGrayBanner(_)
        | Blocks::CyanBanner(_)
        | Blocks::PurpleBanner(_)
        | Blocks::BlueBanner(_)
        | Blocks::BrownBanner(_)
        | Blocks::GreenBanner(_)
        | Blocks::RedBanner(_)
        | Blocks::BlackBanner(_)
        | Blocks::WhiteWallBanner(_)
        | Blocks::OrangeWallBanner(_)
        | Blocks::MagentaWallBanner(_)
        | Blocks::LightBlueWallBanner(_)
        | Blocks::YellowWallBanner(_)
        | Blocks::LimeWallBanner(_)
        | Blocks::PinkWallBanner(_)
        | Blocks::GrayWallBanner(_)
        | Blocks::LightGrayWallBanner(_)
        | Blocks::CyanWallBanner(_)
        | Blocks::PurpleWallBanner(_)
        | Blocks::BlueWallBanner(_)
        | Blocks::BrownWallBanner(_)
        | Blocks::GreenWallBanner(_)
        | Blocks::RedWallBanner(_)
        | Blocks::BlackWallBanner(_)
        | Blocks::Beetroots(_)
        | Blocks::EndGateway
        | Blocks::StructureVoid
        | Blocks::Kelp(_)
        | Blocks::KelpPlant
        | Blocks::DeadTubeCoral(_)
        | Blocks::DeadBrainCoral(_)
        | Blocks::DeadBubbleCoral(_)
        | Blocks::DeadFireCoral(_)
        | Blocks::DeadHornCoral(_)
        | Blocks::TubeCoral(_)
        | Blocks::BrainCoral(_)
        | Blocks::BubbleCoral(_)
        | Blocks::FireCoral(_)
        | Blocks::HornCoral(_)
        | Blocks::DeadTubeCoralFan(_)
        | Blocks::DeadBrainCoralFan(_)
        | Blocks::DeadBubbleCoralFan(_)
        | Blocks::DeadFireCoralFan(_)
        | Blocks::DeadHornCoralFan(_)
        | Blocks::TubeCoralFan(_)
        | Blocks::BrainCoralFan(_)
        | Blocks::BubbleCoralFan(_)
        | Blocks::FireCoralFan(_)
        | Blocks::HornCoralFan(_)
        | Blocks::DeadTubeCoralWallFan(_)
        | Blocks::DeadBrainCoralWallFan(_)
        | Blocks::DeadBubbleCoralWallFan(_)
        | Blocks::DeadFireCoralWallFan(_)
        | Blocks::DeadHornCoralWallFan(_)
        | Blocks::TubeCoralWallFan(_)
        | Blocks::BrainCoralWallFan(_)
        | Blocks::BubbleCoralWallFan(_)
        | Blocks::FireCoralWallFan(_)
        | Blocks::HornCoralWallFan(_)
        | Blocks::SeaPickle(_)
        | Blocks::PottedBamboo
        | Blocks::VoidAir
        | Blocks::CaveAir
        | Blocks::BubbleColumn(_)
        | Blocks::Scaffolding(_)
        | Blocks::Lantern(_)
        | Blocks::SoulLantern(_)
        | Blocks::Shroomlight
        | Blocks::WeepingVines(_)
        | Blocks::WeepingVinesPlant
        | Blocks::TwistingVines(_)
        | Blocks::TwistingVinesPlant
        | Blocks::CrimsonRoots
        | Blocks::CrimsonButton(_)
        | Blocks::WarpedButton(_)
        | Blocks::CrimsonSign(_)
        | Blocks::WarpedSign(_)
        | Blocks::CrimsonWallSign(_)
        | Blocks::WarpedWallSign(_)
        | Blocks::PottedCrimsonFungus
        | Blocks::PottedWarpedFungus
        | Blocks::PottedCrimsonRoots
        | Blocks::PottedWarpedRoots
        | Blocks::Candle(_)
        | Blocks::WhiteCandle(_)
        | Blocks::OrangeCandle(_)
        | Blocks::MagentaCandle(_)
        | Blocks::LightBlueCandle(_)
        | Blocks::YellowCandle(_)
        | Blocks::LimeCandle(_)
        | Blocks::PinkCandle(_)
        | Blocks::GrayCandle(_)
        | Blocks::LightGrayCandle(_)
        | Blocks::CyanCandle(_)
        | Blocks::PurpleCandle(_)
        | Blocks::BlueCandle(_)
        | Blocks::BrownCandle(_)
        | Blocks::GreenCandle(_)
        | Blocks::RedCandle(_)
        | Blocks::BlackCandle(_)
        | Blocks::CaveVines(_)
        | Blocks::CaveVinesPlant(_)
        | Blocks::SporeBlossom
        | Blocks::Azalea
        | Blocks::FloweringAzalea
        | Blocks::PottedAzaleaBush
        | Blocks::PottedFloweringAzaleaBush => false,
        Blocks::Snow(state) if state.layers() == 1 => false,
        _ => true,
    }
}
